blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.HomePageView.as_view(), name="home_page"),
    path('category/', views.CategoryPageView.as_view(), name="category_page"),
    path('about/', views.AboutPageView.as_view(), name="about_page"),
    path('contact/', views.ContactPageView.as_view(), name="contact_page"),
    path('blog/<uuid:blog_id>/', views.BlogDetailPageView.as_view(), name="blog_item"),
]

blogr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="blog")),
]

blog/models.py
from django.db import models
import uuid


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Blog(models.Model):
    id = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid.uuid4
    )
    title = models.CharField(max_length=500)
    body = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title[:30]


class BlogImage(models.Model):
    image = models.ImageField(upload_to="blog_photos/")
    blog = models.ForeignKey(
        Blog, related_name="blog_images", on_delete=models.CASCADE)

blog/views.py
from django.shortcuts import render
from .models import Blog, Category
from django.views.generic import ListView, DetailView, TemplateView
import os
from dotenv import load_dotenv

load_dotenv()


# Home Page View
class HomePageView(ListView):
    model = Blog
    template_name = 'index.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.order_by('?')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        APP_NAME = os.getenv('APP_NAME')

        context['APP_NAME'] = APP_NAME
        return context


class CategoryPageView(TemplateView):
    template_name = 'category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        APP_NAME = os.getenv('APP_NAME')

        context['APP_NAME'] = APP_NAME
        return context


class AboutPageView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        APP_NAME = os.getenv('APP_NAME')

        context['APP_NAME'] = APP_NAME
        return context


class ContactPageView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        APP_NAME = os.getenv('APP_NAME')

        context['APP_NAME'] = APP_NAME
        return context


class BlogDetailPageView(DetailView):
    model = Blog
    template_name = "single-post.html"
    context_object_name = 'blog'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        APP_NAME = os.getenv('APP_NAME')

        context['APP_NAME'] = APP_NAME
        return context

templates/_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta content="Blogr" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">

    <!-- Template Main CSS Files -->
    <link href="{% static 'assets/css/variables.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

    <title>Bløgɾ - {% block title %}{% endblock %}</title>
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="{% url 'blog:home_page' %}" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1>Bløgɾ</h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a href="{% url 'blog:home_page' %}">Blog</a></li>
                    <li><a href="single-post.html">Single Post</a></li>
                    <li class="dropdown"><a href="{% url 'blog:category_page' %}"><span>Categories</span> <i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            <li><a href="search-result.html">Search Result</a></li>
                            <li><a href="#">Business</a></li>
                            <li><a href="#">Culture</a></li>
                            <li><a href="#">Sport</a></li>
                            <li><a href="#">Food</a></li>
                            <li><a href="#">Politics</a></li>
                            <li><a href="#">Celebrity</a></li>
                            <li><a href="#">Startups</a></li>
                            <li><a href="#">Travel</a></li>

                        </ul>
                    </li>

                    <li><a href="{% url 'blog:about_page' %}">About</a></li>
                    <li><a href="{% url 'blog:contact_page' %}">Contact</a></li>
                </ul>
            </nav><!-- .navbar -->

            <div class="position-relative">
                <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
                <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
                <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

                <a href="#" class="mx-2 js-search-open"><span class="bi-search"></span></a>
                <i class="bi bi-list mobile-nav-toggle"></i>

                <!-- ======= Search Form ======= -->
                <div class="search-form-wrap js-search-form-wrap">
                    <form action="search-result.html" class="search-form">
                        <span class="icon bi-search"></span>
                        <input type="text" placeholder="Search" class="form-control">
                        <button class="btn js-search-close"><span class="bi-x"></span></button>
                    </form>
                </div><!-- End Search Form -->

            </div>

        </div>

    </header><!-- End Header -->

    {% block content %}

    {% endblock content %}

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-content">
            <div class="container">

                <div class="row g-5">
                    <div class="col-lg-4">
                        <h3 class="footer-heading">About Bløgɾ</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem
                            deleniti
                            voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis qui
                            aliquid
                            blanditiis omnis quae. Explicabo?</p>
                        <p><a href="about.html" class="footer-link-more">Learn More</a></p>
                    </div>
                    <div class="col-6 col-lg-2">
                        <h3 class="footer-heading">Navigation</h3>
                        <ul class="footer-links list-unstyled">
                            <li><a href="{% url 'blog:home_page' %}"><i class="bi bi-chevron-right"></i> Home</a></li>
                            <li><a href="{% url 'blog:home_page' %}"><i class="bi bi-chevron-right"></i> Blog</a></li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i>
                                    Categories</a></li>
                            <li><a href="single-post.html"><i class="bi bi-chevron-right"></i> Single Post</a></li>
                            <li><a href="{% url 'blog:about_page' %}"><i class="bi bi-chevron-right"></i> About us</a>
                            </li>
                            <li><a href="{% url 'blog:contact_page' %}"><i class="bi bi-chevron-right"></i> Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6 col-lg-2">
                        <h3 class="footer-heading">Categories</h3>
                        <ul class="footer-links list-unstyled">
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i>
                                    Business</a></li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i> Culture</a>
                            </li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i> Sport</a>
                            </li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i> Food</a>
                            </li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i>
                                    Politics</a></li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i>
                                    Celebrity</a></li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i>
                                    Startups</a></li>
                            <li><a href="{% url 'blog:category_page' %}"><i class="bi bi-chevron-right"></i> Travel</a>
                            </li>

                        </ul>
                    </div>

                    <div class="col-lg-4">
                        <h3 class="footer-heading">Recent Posts</h3>

                        <ul class="footer-links footer-blog-entry list-unstyled">
                            <li>
                                <a href="single-post.html" class="d-flex align-items-center">
                                    <img src="assets/img/post-sq-1.jpg" alt="" class="img-fluid me-3">
                                    <div>
                                        <div class="post-meta d-block"><span class="date">Culture</span> <span
                                                class="mx-1">&bullet;</span>
                                            <span>Jul 5th '22</span>
                                        </div>
                                        <span>5 Great Startup Tips for Female Founders</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="single-post.html" class="d-flex align-items-center">
                                    <img src="assets/img/post-sq-2.jpg" alt="" class="img-fluid me-3">
                                    <div>
                                        <div class="post-meta d-block"><span class="date">Culture</span> <span
                                                class="mx-1">&bullet;</span>
                                            <span>Jul 5th '22</span>
                                        </div>
                                        <span>What is the son of Football Coach John Gruden, Deuce Gruden doing
                                            Now?</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="single-post.html" class="d-flex align-items-center">
                                    <img src="assets/img/post-sq-3.jpg" alt="" class="img-fluid me-3">
                                    <div>
                                        <div class="post-meta d-block"><span class="date">Culture</span> <span
                                                class="mx-1">&bullet;</span>
                                            <span>Jul 5th '22</span>
                                        </div>
                                        <span>Life Insurance And Pregnancy: A Working Mom’s Guide</span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="single-post.html" class="d-flex align-items-center">
                                    <img src="assets/img/post-sq-4.jpg" alt="" class="img-fluid me-3">
                                    <div>
                                        <div class="post-meta d-block"><span class="date">Culture</span> <span
                                                class="mx-1">&bullet;</span>
                                            <span>Jul 5th '22</span>
                                        </div>
                                        <span>How to Avoid Distraction and Stay Focused During Video Calls?</span>
                                    </div>
                                </a>
                            </li>

                        </ul>

                    </div>
                </div>
            </div>
        </div>

        <div class="footer-legal">
            <div class="container">

                <div class="row justify-content-between">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <div class="copyright">
                            © Copyright <strong><span>Bløgɾ</span></strong>. All Rights Reserved
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>

                    </div>

                </div>

            </div>
        </div>

    </footer>

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>


</html>

templates/about.html
{% extends "_base.html" %}
{% load static %}
{% block title %}About{% endblock %}

{% block content %}
<main id="main">
  <section>
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-12 text-center mb-5">
          <h1 class="page-title">About us</h1>
        </div>
      </div>

      <div class="row mb-5">

        <div class="d-md-flex post-entry-2 half">
          <a href="#" class="me-4 thumbnail">
            <img src="assets/img/post-landscape-2.jpg" alt="" class="img-fluid">
          </a>
          <div class="ps-md-5 mt-4 mt-md-0">
            <div class="post-meta mt-4">About us</div>
            <h2 class="mb-4 display-4">Company History</h2>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
              non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore?
              Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
            <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores quasi
              eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente beatae ullam.
              Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis eligendi.</p>
          </div>
        </div>

        <div class="d-md-flex post-entry-2 half mt-5">
          <a href="#" class="me-4 thumbnail order-2">
            <img src="assets/img/post-landscape-1.jpg" alt="" class="img-fluid">
          </a>
          <div class="pe-md-5 mt-4 mt-md-0">
            <div class="post-meta mt-4">Mission &amp; Vision</div>
            <h2 class="mb-4 display-4">Mission &amp; Vision</h2>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
              non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore?
              Voluptatum in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
            <p>Fugit eaque illum blanditiis, quo exercitationem maiores autem laudantium unde excepturi dolores quasi
              eos vero harum ipsa quam laborum illo aut facere voluptates aliquam adipisci sapiente beatae ullam.
              Tempora culpa iusto illum accusantium cum hic quisquam dolor placeat officiis eligendi.</p>
          </div>
        </div>

      </div>

    </div>
  </section>

  <section class="mb-5 bg-light py-5">
    <div class="container" data-aos="fade-up">
      <div class="row justify-content-between align-items-lg-center">
        <div class="col-lg-5 mb-4 mb-lg-0">
          <h2 class="display-4 mb-4">Latest News</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, rem eaque vel est asperiores iste pariatur
            placeat molestias, rerum provident ea maiores debitis eum earum esse quas architecto! Minima, voluptatum!
            Minus tempora distinctio quo sint est blanditiis voluptate eos. Commodi dolore nesciunt culpa adipisci nemo
            expedita suscipit autem dolorum rerum?</p>
          <p>At magni dolore ullam odio sapiente ipsam, numquam eius minus animi inventore alias quam fugit corrupti
            error iste laboriosam dolorum culpa doloremque eligendi repellat iusto vel impedit odit cum. Sequi atque
            molestias nesciunt rem eum pariatur quibusdam deleniti saepe eius maiores porro quam, praesentium ipsa
            deserunt laboriosam adipisci. Optio, animi!</p>
          <p><a href="#" class="more">View All Blog Posts</a></p>
        </div>
        <div class="col-lg-6">
          <div class="row">
            <div class="col-6">
              <img src="assets/img/post-portrait-3.jpg" alt="" class="img-fluid mb-4">
            </div>
            <div class="col-6 mt-4">
              <img src="assets/img/post-portrait-4.jpg" alt="" class="img-fluid mb-4">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-12 text-center mb-5">
          <div class="row justify-content-center">
            <div class="col-lg-6">
              <h2 class="display-4">Our Team</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil sint sed, fugit distinctio ad eius
                itaque deserunt doloribus harum excepturi laudantium sit officiis et eaque blanditiis. Dolore natus
                excepturi recusandae.</p>
            </div>
          </div>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-1.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Cameron Williamson</h4>
          <span class="d-block mb-3 text-uppercase">Founder &amp; CEO</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-2.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Wade Warren</h4>
          <span class="d-block mb-3 text-uppercase">Founder, VP</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-3.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Jane Cooper</h4>
          <span class="d-block mb-3 text-uppercase">Editor Staff</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-4.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Cameron Williamson</h4>
          <span class="d-block mb-3 text-uppercase">Editor Staff</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-5.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Cameron Williamson</h4>
          <span class="d-block mb-3 text-uppercase">Editor Staff</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
        <div class="col-lg-4 text-center mb-5">
          <img src="assets/img/person-6.jpg" alt="" class="img-fluid rounded-circle w-50 mb-4">
          <h4>Cameron Williamson</h4>
          <span class="d-block mb-3 text-uppercase">Editor Staff</span>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis, perspiciatis repellat maxime, adipisci
            non ipsam at itaque rerum vitae, necessitatibus nulla animi expedita cumque provident inventore? Voluptatum
            in tempora earum deleniti, culpa odit veniam, ea reiciendis sunt ullam temporibus aut!</p>
        </div>
      </div>
    </div>
  </section>

</main><!-- End #main -->
{% endblock content %}